chore/no longer import libwinpthread-1.dll
joshuef/peruse pull request #31
Opened 2018-01-09 20:16 UTC by hunterlester

Tested successfully on Windows 10 by executing browser, visiting safe sites, and interacting with network with API playground.

2018-01-10 18:12 UTC, bochaco requested changes
@hunterlester , we also need to remove the lib from the `app/package.json`.
Also, don't you have a VM with a clean Windows (i.e. without any dev tools libs installed) to understand if we effectively don't need this library anymore as it's part of the base set of Windows dll's ?

2018-01-17 09:12 UTC, joshuef requested changes

2018-01-17 09:12 UTC, joshuef commented on app/extensions/safe/ffi/lib.js
> -          ffi.DynamicLibrary(path.resolve(__dirname, CONSTANTS.LIB_PATH.PTHREAD), mode);
If we're not needing the lib, we should also remove the relevant lines from the `CONSTANTS.LIB_PATH`, too.

2018-01-19 15:12 UTC, bochaco approved these changes

2018-01-22 08:29 UTC, joshuef approved these changes

2018-01-22 08:29 UTC, merged