feat/mock: adds preloaded MockVault that comes with account and brows…
joshuef/peruse pull request #78
Opened 2018-04-02 15:02 UTC by hunterlester

…er API tool

2018-05-22 10:23 UTC, joshuef requested changes
I think we should look at the `new` flag at the least, but a couple more things to consider here also...

2018-05-22 10:23 UTC, joshuef commented on README.md
> +Additionally, the `--new` flag can be passed in order to get the following features preloaded in `mock` network mode:
I wonder if `new` makes sense here (to me that would signify a fresh network, without anything).

What if we went with `loadMock`? That could default to our added mock file, or (perhaps) we add the ability to pass a file also. That wouldn't be that much more on top of what you already have @hunterlester (check for file, that it exists..., otherwise load default).

Might be out of scope for these changes also (though I still think `new` is a bit misleading).

2018-05-22 10:23 UTC, joshuef commented on app/main.development.js
> +    fs.readFile(path.join(__dirname, '..', 'MockVault'), (err, data) => {
Can we use a constant for this 'default' mock vault, instead of `__dirname, '..', 'MockVault'`.

I would also suggest we rename the file in the repo to be 'dev Mock', perhaps? (Although that raises a question of what should be loaded by default anyway..., this one with a couple of nice preloads, or a completely fresh one?)

2018-05-22 15:42 UTC, joshuef commented on README.md
> +Additionally, the `--new` flag can be passed in order to get the following features preloaded in `mock` network mode:
Okay, after our recent HO, the loading of alternate files is for sure out of scope for now.

2018-05-23 20:14 UTC, hunterlester commented on app/main.development.js
> +    fs.readFile(path.join(__dirname, '..', 'MockVault'), (err, data) => {
I was thinking anything useful to get started development. In this PR, the `MockVault` file is loaded with the api playground already hosted at `safe://codeplay.discover` (i think that's the URL).

2018-05-24 13:17 UTC, joshuef commented
@hunter I'm not getting any account with those creds.

It does appear to be overwriting the file, but I can't tell if it's those creds that are wrong or what's going on...

2018-05-30 10:02 UTC, joshuef commented
@hunterlester i'm not sure of the cause, but neither are working for me in this PR.

2018-05-30 10:03 UTC, joshuef requested changes
neither login nor API site are working on osx

2018-06-22 06:28 UTC, joshuef commented
this is actually in master now (was rolled into dev, i might have broken the commit ref though rebasing)

2018-06-22 06:28 UTC, closed without merging